# Generated by Django 5.2.4 on 2025-07-11 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='program',
            options={'managed': False},
        ),
    ]
