# Generated by Django 5.2.4 on 2025-07-25 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='annualbudget',
            options={'get_latest_by': 'year', 'managed': False},
        ),
    ]
